"""
PDF Report Exporter — Neomnix Platform.
Branded executive PDF reports with proper compliance formatting.
Fix 12: Added logo placeholder, page numbers, color branding, and professional layout.
"""
from fpdf import FPDF
from datetime import datetime
import os


class PDFReportExporter:
    """Generates branded executive PDF reports for compliance frameworks."""

    BRAND_COLOR = (30, 58, 138)      # Deep blue
    HEADER_COLOR = (37, 99, 235)     # Blue
    CRITICAL_COLOR = (220, 38, 38)   # Red
    HIGH_COLOR = (234, 88, 12)       # Orange
    MEDIUM_COLOR = (202, 138, 4)     # Yellow
    TEXT_COLOR = (31, 41, 55)        # Dark gray
    SUBTLE_COLOR = (107, 114, 128)   # Gray

    def __init__(self):
        self.output_dir = os.path.join(
            os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
            "reports", "pdf"
        )
        os.makedirs(self.output_dir, exist_ok=True)
        # Read platform name from environment — allows white-label PDF branding
        self.platform_name = os.getenv("PLATFORM_NAME", os.getenv("ADMIN_EMAIL", "").split("@")[-1].split(".")[0].upper() + " GRC")
        if not self.platform_name or len(self.platform_name) < 3:
            self.platform_name = "Neomnix GRC"

    def generate_report(self, framework: str, findings: list, status: str, confidence: float, job_id: str) -> str:
        """Generate a branded executive PDF report."""
        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=25)
        pdf.add_page()

        # --- Cover / Header Section ---
        self._draw_header(pdf, framework, job_id, status, confidence)

        # --- Executive Summary ---
        pdf.ln(5)
        self._section_title(pdf, "Executive Summary")

        total = len(findings)
        critical_count = sum(1 for f in findings if f.get('severity') == 'critical')
        high_count = sum(1 for f in findings if f.get('severity') == 'high')
        medium_count = sum(1 for f in findings if f.get('severity') == 'medium')

        pdf.set_font("Helvetica", size=10)
        pdf.set_text_color(*self.TEXT_COLOR)

        summary_lines = [
            f"This report presents the results of an automated compliance scan against the {framework} framework.",
            f"A total of {total} finding(s) were identified during the assessment.",
            f"",
            f"  - Critical: {critical_count}",
            f"  - High: {high_count}",
            f"  - Medium: {medium_count}",
            f"",
            f"Overall Determination: {status.upper().replace('_', ' ')}",
            f"Confidence Score: {confidence:.1%}",
        ]

        for line in summary_lines:
            pdf.cell(0, 6, line, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(5)

        # --- Detailed Findings ---
        if findings:
            self._section_title(pdf, "Detailed Findings")

            for i, finding in enumerate(findings, 1):
                severity = finding.get('severity', 'unknown').upper()
                desc = finding.get('description', 'No description')
                evidence = finding.get('evidence', 'No evidence provided')

                # Severity color
                if severity == 'CRITICAL':
                    pdf.set_text_color(*self.CRITICAL_COLOR)
                elif severity == 'HIGH':
                    pdf.set_text_color(*self.HIGH_COLOR)
                elif severity == 'MEDIUM':
                    pdf.set_text_color(*self.MEDIUM_COLOR)
                else:
                    pdf.set_text_color(*self.TEXT_COLOR)

                pdf.set_font("Helvetica", "B", 10)
                pdf.cell(0, 7, f"Finding #{i} [{severity}]", new_x="LMARGIN", new_y="NEXT")

                pdf.set_text_color(*self.TEXT_COLOR)
                pdf.set_font("Helvetica", size=9)
                pdf.set_x(pdf.l_margin)
                pdf.multi_cell(0, 5, f"Description: {desc}")
                pdf.set_font("Helvetica", "I", 8)
                pdf.set_text_color(*self.SUBTLE_COLOR)
                pdf.set_x(pdf.l_margin)
                pdf.multi_cell(0, 5, f"Evidence: {evidence}")
                pdf.ln(3)

        # --- Legal Disclaimer ---
        self._section_title(pdf, "Legal Disclaimer")
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(*self.SUBTLE_COLOR)
        pdf.multi_cell(0, 4,
            "This report is generated by the Neomnix Platform Compliance Platform. "
            "It is intended for authorized personnel only and should not be distributed "
            "without proper authorization. The findings represent a point-in-time assessment "
            "and may not reflect the current security posture. This report does not constitute "
            "legal or professional compliance advice. Organizations should consult qualified "
            "compliance professionals for formal assessments."
        )

        # --- Page Numbers (footer) ---
        total_pages = pdf.page_no()
        for page_num in range(1, total_pages + 1):
            pdf.page = page_num
            pdf.set_y(-15)
            pdf.set_font("Helvetica", "I", 7)
            pdf.set_text_color(*self.SUBTLE_COLOR)
            pdf.cell(0, 10, f"{self.platform_name}  |  Page {page_num} of {total_pages}  |  Confidential", align="C")

        # --- Save ---
        filename = f"{framework}_{job_id}.pdf"
        filepath = os.path.join(self.output_dir, filename)
        pdf.output(filepath)

        return filepath

    def _draw_header(self, pdf: FPDF, framework: str, job_id: str, status: str, confidence: float):
        """Draw branded header with company name and scan metadata."""
        # Top bar
        pdf.set_fill_color(*self.BRAND_COLOR)
        pdf.rect(0, 0, 210, 45, style='F')

        # Company name
        pdf.set_y(8)
        pdf.set_font("Helvetica", "B", 20)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(0, 10, self.platform_name.upper(), align="C", new_x="LMARGIN", new_y="NEXT")

        # Framework subtitle
        pdf.set_font("Helvetica", size=12)
        pdf.set_text_color(191, 219, 254)
        pdf.cell(0, 7, f"{framework} Compliance Report", align="C", new_x="LMARGIN", new_y="NEXT")

        # Metadata line
        pdf.set_font("Helvetica", size=8)
        pdf.set_text_color(147, 197, 253)
        meta = f"Scan ID: {job_id[:12]}...  |  Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}  |  Status: {status.upper()}"
        pdf.cell(0, 5, meta, align="C", new_x="LMARGIN", new_y="NEXT")

        pdf.set_y(50)

    def _section_title(self, pdf: FPDF, title: str):
        """Draw a styled section title with underline."""
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(*self.HEADER_COLOR)
        pdf.cell(0, 8, title, new_x="LMARGIN", new_y="NEXT")
        # Underline
        pdf.set_draw_color(*self.HEADER_COLOR)
        pdf.set_line_width(0.3)
        pdf.line(pdf.get_x(), pdf.get_y(), pdf.get_x() + 190, pdf.get_y())
        pdf.ln(3)
