"""remove_stripe_billing_and_legacy_scan_fields

Revision ID: 1e518a1fd67f
Revises: 
Create Date: 2026-06-07 19:41:38.004520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e518a1fd67f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_tenant_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_column('scan_jobs', 'completed_at')
    op.drop_column('scan_jobs', 'final_intensity')
    op.drop_index(op.f('ix_tenants_stripe_customer_id'), table_name='tenants')
    op.drop_column('tenants', 'stripe_customer_id')
    op.drop_column('tenants', 'logo_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('logo_url', sa.VARCHAR(), nullable=True))
    op.add_column('tenants', sa.Column('stripe_customer_id', sa.VARCHAR(), nullable=True))
    op.create_index(op.f('ix_tenants_stripe_customer_id'), 'tenants', ['stripe_customer_id'], unique=1)
    op.add_column('scan_jobs', sa.Column('final_intensity', sa.INTEGER(), nullable=True))
    op.add_column('scan_jobs', sa.Column('completed_at', sa.DATETIME(), nullable=True))
    op.create_table('subscriptions',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('stripe_subscription_id', sa.VARCHAR(), nullable=True),
    sa.Column('stripe_product_id', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('tier', sa.VARCHAR(), nullable=True),
    sa.Column('price_per_month', sa.FLOAT(), nullable=True),
    sa.Column('seats_limit', sa.INTEGER(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('ends_at', sa.DATETIME(), nullable=True),
    sa.Column('trial_ends_at', sa.DATETIME(), nullable=True),
    sa.Column('auto_renew', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    op.create_index(op.f('ix_subscriptions_tenant_id'), 'subscriptions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    # ### end Alembic commands ###
